### PR TITLE
Added ham menu for smaller screens

### LINKED ISSUE #2: Add Hamburger menu in navbar
Temporarily font is decreased for smaller screen but add hamburger in navbar for smaller screen.

### PR DESCRIPTION
**Pull request by Vaishali785**
Fixes #2 

Before click
Screenshot 2023-10-02 at 5 11 20 PM

After click
Screenshot 2023-10-02 at 5 11 26 PM

### CODE REVIEW

**Comment by itshypon** [comment]
@Vaishali785 Cool, looks like it has some empty space on both sides. Can you modify it so that it pops up in middle or contain less empty space around it.
You can take inspiration from this - 
image

**Comment by itshypon** [comment]
@Vaishali785 Close button is fine because we have to provide the option to close. I will do some border and other UI changes to make it a little better. So, its fine for MVP. You can commit these changes.

**Comment by Vaishali785** [comment]
> @Vaishali785 Close button is fine because we have to provide the option to close. I will do some border and other UI changes to make it a little better. So, its fine for MVP. You can commit these changes.

okay @itshypon I've added the changes in the PR.

**Comment by itshypon** [comment]
@Vaishali785 When I open it in mobile, it has some issues like blurred navbar and pop-up should be fixed at center.
Check deploy-preview in mobile.

**Comment by Vaishali785** [comment]
> @Vaishali785 When I open it in mobile, it has some issues like blurred navbar and pop-up should be fixed at center. Check deploy-preview in mobile.

I have made some changes, can you check it again? As this is looking fine in my mobile preview.

**Comment by itshypon** [comment]
@Vaishali785 It's fine now. Will merge it !

**Pull request merged**
